version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  bff:
    build: 
      context: ./bff
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - nginx-proxy
      - backend
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    networks:
      - nginx-proxy
    environment:
      BASE_URL: /api/api
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 5000:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - bff
    networks:
      - nginx-proxy

volumes:
  postgres-data:

networks:
  nginx-proxy:
    driver: bridge
  backend:
    driver: bridge